
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: docs/imports.ipynb

from torch.utils.data import DataLoader
from torch import tensor
import torch
import matplotlib.pyplot as plt

from functools import partial
from typing import *
import re
import pickle
import gzip
import math

from fastai import datasets
from torch.utils.data import DataLoader
#SequentialSampler, RandomSampler
from torch import optim
from torch import nn
import torch.nn.functional as F