
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: docs/helper_helper.ipynb

import sys
from pathlib import Path
sys.path.append(Path.cwd().parent.as_posix()+'/BlackBoxAI')
from imports import *
from api.learner import Learner

def accuracy(out, yb): return (torch.argmax(out, dim=1)==yb).float().mean()

def create_learner(model_func, loss_func, data):
    return Learner(*model_func(data), loss_func, data)